name: ${project.name}
version: '${project.version}'
main: de.eztxm.smp.SMP
api-version: '1.21'
authors: [ ezTxmMC, SyntaxJason, TntTastisch ]
load: STARTUP

dependencies:
  bootstrap:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
